--Obtener información de un procedure 
-- INFORMATION_SCHEMA.ROUTINES
-- INFORMATION_SCHEMA.TABLES
-- INFORMATION_SCHEMA.COLUMNS

SELECT SPECIFIC_NAME
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_TYPE = 'PROCEDURE'
	and ROUTINE_SCHEMA = 'dbo'
	and ROUTINE_DEFINITION LIKE '%catPerfilProducto%'
